### ISSUE TITLE
Link TelescopePreviewLine to TelescopeSelection and CurSearch to Search

### ISSUE THREAD

**Issue by paulrouget** [xero/miasma.nvim#3]
Without these, the search line in the telescope preview, and the current search result are not highlighted.

```vim
hi link TelescopePreviewLine TelescopeSelection
hi link CurSearch Search
```

**Comment by tudor07** [comment]
is there any way to add these manually until I wait for the official fix?

**Comment by xero** [comment]
cool. i've updated the dev branch to create new new highlights, generated a new version, then pushed it to main. appreciate ya!
